# Dockerfile for Truffle migrations
FROM node:20-alpine

WORKDIR /app

RUN npm install -g truffle

# Copy contract configuration and source
COPY truffle-config.js .
COPY contracts ./contracts
COPY migrations ./migrations

# This command will run when the service starts
CMD ["truffle", "migrate", "--network", "docker", "--reset"]